// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: giwa/jit/v1/jit.proto

package jitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockEventKind int32

const (
	BlockEventKind_BLOCK_EVENT_KIND_UNSPECIFIED       BlockEventKind = 0
	BlockEventKind_BLOCK_EVENT_KIND_BEACON_WITHDRAWAL BlockEventKind = 1
)

// Enum value maps for BlockEventKind.
var (
	BlockEventKind_name = map[int32]string{
		0: "BLOCK_EVENT_KIND_UNSPECIFIED",
		1: "BLOCK_EVENT_KIND_BEACON_WITHDRAWAL",
	}
	BlockEventKind_value = map[string]int32{
		"BLOCK_EVENT_KIND_UNSPECIFIED":       0,
		"BLOCK_EVENT_KIND_BEACON_WITHDRAWAL": 1,
	}
)

func (x BlockEventKind) Enum() *BlockEventKind {
	p := new(BlockEventKind)
	*p = x
	return p
}

func (x BlockEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_giwa_jit_v1_jit_proto_enumTypes[0].Descriptor()
}

func (BlockEventKind) Type() protoreflect.EnumType {
	return &file_giwa_jit_v1_jit_proto_enumTypes[0]
}

func (x BlockEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockEventKind.Descriptor instead.
func (BlockEventKind) EnumDescriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{0}
}

type HashValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashValue) Reset() {
	*x = HashValue{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashValue) ProtoMessage() {}

func (x *HashValue) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashValue.ProtoReflect.Descriptor instead.
func (*HashValue) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{0}
}

func (x *HashValue) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *HashValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentHash   *HashValue             `protobuf:"bytes,1,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Locator       string                 `protobuf:"bytes,2,opt,name=locator,proto3" json:"locator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactRef) GetContentHash() *HashValue {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *ArtifactRef) GetLocator() string {
	if x != nil {
		return x.Locator
	}
	return ""
}

type BlockRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   string                 `protobuf:"bytes,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash     string                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRef) Reset() {
	*x = BlockRef{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRef) ProtoMessage() {}

func (x *BlockRef) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRef.ProtoReflect.Descriptor instead.
func (*BlockRef) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{2}
}

func (x *BlockRef) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *BlockRef) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BlockRef) GetBlockTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BlockTime
	}
	return nil
}

type BlockRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromBlock     string                 `protobuf:"bytes,1,opt,name=from_block,json=fromBlock,proto3" json:"from_block,omitempty"`
	ToBlock       string                 `protobuf:"bytes,2,opt,name=to_block,json=toBlock,proto3" json:"to_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRange) Reset() {
	*x = BlockRange{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRange) ProtoMessage() {}

func (x *BlockRange) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRange.ProtoReflect.Descriptor instead.
func (*BlockRange) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{3}
}

func (x *BlockRange) GetFromBlock() string {
	if x != nil {
		return x.FromBlock
	}
	return ""
}

func (x *BlockRange) GetToBlock() string {
	if x != nil {
		return x.ToBlock
	}
	return ""
}

type TransactionLocator struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber      string                 `protobuf:"bytes,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TransactionIndex uint32                 `protobuf:"varint,2,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	MatchBits        uint32                 `protobuf:"varint,3,opt,name=match_bits,json=matchBits,proto3" json:"match_bits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionLocator) Reset() {
	*x = TransactionLocator{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLocator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLocator) ProtoMessage() {}

func (x *TransactionLocator) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLocator.ProtoReflect.Descriptor instead.
func (*TransactionLocator) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionLocator) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *TransactionLocator) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *TransactionLocator) GetMatchBits() uint32 {
	if x != nil {
		return x.MatchBits
	}
	return 0
}

type BlockEventLocator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   string                 `protobuf:"bytes,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	EventKind     BlockEventKind         `protobuf:"varint,2,opt,name=event_kind,json=eventKind,proto3,enum=giwa.jit.v1.BlockEventKind" json:"event_kind,omitempty"`
	EventIndex    uint64                 `protobuf:"varint,3,opt,name=event_index,json=eventIndex,proto3" json:"event_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockEventLocator) Reset() {
	*x = BlockEventLocator{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockEventLocator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockEventLocator) ProtoMessage() {}

func (x *BlockEventLocator) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockEventLocator.ProtoReflect.Descriptor instead.
func (*BlockEventLocator) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{5}
}

func (x *BlockEventLocator) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *BlockEventLocator) GetEventKind() BlockEventKind {
	if x != nil {
		return x.EventKind
	}
	return BlockEventKind_BLOCK_EVENT_KIND_UNSPECIFIED
}

func (x *BlockEventLocator) GetEventIndex() uint64 {
	if x != nil {
		return x.EventIndex
	}
	return 0
}

type CandidateLocator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Position:
	//
	//	*CandidateLocator_Transaction
	//	*CandidateLocator_BlockEvent
	Position      isCandidateLocator_Position `protobuf_oneof:"position"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateLocator) Reset() {
	*x = CandidateLocator{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateLocator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateLocator) ProtoMessage() {}

func (x *CandidateLocator) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateLocator.ProtoReflect.Descriptor instead.
func (*CandidateLocator) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{6}
}

func (x *CandidateLocator) GetPosition() isCandidateLocator_Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CandidateLocator) GetTransaction() *TransactionLocator {
	if x != nil {
		if x, ok := x.Position.(*CandidateLocator_Transaction); ok {
			return x.Transaction
		}
	}
	return nil
}

func (x *CandidateLocator) GetBlockEvent() *BlockEventLocator {
	if x != nil {
		if x, ok := x.Position.(*CandidateLocator_BlockEvent); ok {
			return x.BlockEvent
		}
	}
	return nil
}

type isCandidateLocator_Position interface {
	isCandidateLocator_Position()
}

type CandidateLocator_Transaction struct {
	Transaction *TransactionLocator `protobuf:"bytes,1,opt,name=transaction,proto3,oneof"`
}

type CandidateLocator_BlockEvent struct {
	BlockEvent *BlockEventLocator `protobuf:"bytes,2,opt,name=block_event,json=blockEvent,proto3,oneof"`
}

func (*CandidateLocator_Transaction) isCandidateLocator_Position() {}

func (*CandidateLocator_BlockEvent) isCandidateLocator_Position() {}

type MaterializeAccountSelectionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IndexSnapshotId string                 `protobuf:"bytes,1,opt,name=index_snapshot_id,json=indexSnapshotId,proto3" json:"index_snapshot_id,omitempty"`
	ChainStore      string                 `protobuf:"bytes,2,opt,name=chain_store,json=chainStore,proto3" json:"chain_store,omitempty"`
	ChainId         string                 `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	GenesisHash     string                 `protobuf:"bytes,4,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`
	Address         string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Range           *BlockRange            `protobuf:"bytes,6,opt,name=range,proto3" json:"range,omitempty"`
	EvidenceProfile string                 `protobuf:"bytes,7,opt,name=evidence_profile,json=evidenceProfile,proto3" json:"evidence_profile,omitempty"`
	ProfileHash     string                 `protobuf:"bytes,8,opt,name=profile_hash,json=profileHash,proto3" json:"profile_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MaterializeAccountSelectionRequest) Reset() {
	*x = MaterializeAccountSelectionRequest{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializeAccountSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializeAccountSelectionRequest) ProtoMessage() {}

func (x *MaterializeAccountSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializeAccountSelectionRequest.ProtoReflect.Descriptor instead.
func (*MaterializeAccountSelectionRequest) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{7}
}

func (x *MaterializeAccountSelectionRequest) GetIndexSnapshotId() string {
	if x != nil {
		return x.IndexSnapshotId
	}
	return ""
}

func (x *MaterializeAccountSelectionRequest) GetChainStore() string {
	if x != nil {
		return x.ChainStore
	}
	return ""
}

func (x *MaterializeAccountSelectionRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *MaterializeAccountSelectionRequest) GetGenesisHash() string {
	if x != nil {
		return x.GenesisHash
	}
	return ""
}

func (x *MaterializeAccountSelectionRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MaterializeAccountSelectionRequest) GetRange() *BlockRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *MaterializeAccountSelectionRequest) GetEvidenceProfile() string {
	if x != nil {
		return x.EvidenceProfile
	}
	return ""
}

func (x *MaterializeAccountSelectionRequest) GetProfileHash() string {
	if x != nil {
		return x.ProfileHash
	}
	return ""
}

type AccountCandidateSelectionRef struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SelectionId           string                 `protobuf:"bytes,1,opt,name=selection_id,json=selectionId,proto3" json:"selection_id,omitempty"`
	SelectionDigest       string                 `protobuf:"bytes,2,opt,name=selection_digest,json=selectionDigest,proto3" json:"selection_digest,omitempty"`
	LogicalCandidateCount uint64                 `protobuf:"varint,3,opt,name=logical_candidate_count,json=logicalCandidateCount,proto3" json:"logical_candidate_count,omitempty"`
	SelectionArtifact     *ArtifactRef           `protobuf:"bytes,4,opt,name=selection_artifact,json=selectionArtifact,proto3" json:"selection_artifact,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AccountCandidateSelectionRef) Reset() {
	*x = AccountCandidateSelectionRef{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCandidateSelectionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCandidateSelectionRef) ProtoMessage() {}

func (x *AccountCandidateSelectionRef) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCandidateSelectionRef.ProtoReflect.Descriptor instead.
func (*AccountCandidateSelectionRef) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{8}
}

func (x *AccountCandidateSelectionRef) GetSelectionId() string {
	if x != nil {
		return x.SelectionId
	}
	return ""
}

func (x *AccountCandidateSelectionRef) GetSelectionDigest() string {
	if x != nil {
		return x.SelectionDigest
	}
	return ""
}

func (x *AccountCandidateSelectionRef) GetLogicalCandidateCount() uint64 {
	if x != nil {
		return x.LogicalCandidateCount
	}
	return 0
}

func (x *AccountCandidateSelectionRef) GetSelectionArtifact() *ArtifactRef {
	if x != nil {
		return x.SelectionArtifact
	}
	return nil
}

type MaterializeAccountSelectionResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Selection     *AccountCandidateSelectionRef `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializeAccountSelectionResponse) Reset() {
	*x = MaterializeAccountSelectionResponse{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializeAccountSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializeAccountSelectionResponse) ProtoMessage() {}

func (x *MaterializeAccountSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializeAccountSelectionResponse.ProtoReflect.Descriptor instead.
func (*MaterializeAccountSelectionResponse) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{9}
}

func (x *MaterializeAccountSelectionResponse) GetSelection() *AccountCandidateSelectionRef {
	if x != nil {
		return x.Selection
	}
	return nil
}

type GetAccountSelectionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SelectionId    string                 `protobuf:"bytes,1,opt,name=selection_id,json=selectionId,proto3" json:"selection_id,omitempty"`
	ExpectedDigest string                 `protobuf:"bytes,2,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAccountSelectionRequest) Reset() {
	*x = GetAccountSelectionRequest{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSelectionRequest) ProtoMessage() {}

func (x *GetAccountSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSelectionRequest.ProtoReflect.Descriptor instead.
func (*GetAccountSelectionRequest) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{10}
}

func (x *GetAccountSelectionRequest) GetSelectionId() string {
	if x != nil {
		return x.SelectionId
	}
	return ""
}

func (x *GetAccountSelectionRequest) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

type AccountCandidateSelection struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	Ref             *AccountCandidateSelectionRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	IndexSnapshotId string                        `protobuf:"bytes,2,opt,name=index_snapshot_id,json=indexSnapshotId,proto3" json:"index_snapshot_id,omitempty"`
	ChainId         string                        `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	GenesisHash     string                        `protobuf:"bytes,4,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`
	Address         string                        `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Range           *BlockRange                   `protobuf:"bytes,6,opt,name=range,proto3" json:"range,omitempty"`
	EvidenceProfile string                        `protobuf:"bytes,7,opt,name=evidence_profile,json=evidenceProfile,proto3" json:"evidence_profile,omitempty"`
	ProfileHash     string                        `protobuf:"bytes,8,opt,name=profile_hash,json=profileHash,proto3" json:"profile_hash,omitempty"`
	Candidates      []*CandidateLocator           `protobuf:"bytes,9,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountCandidateSelection) Reset() {
	*x = AccountCandidateSelection{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCandidateSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCandidateSelection) ProtoMessage() {}

func (x *AccountCandidateSelection) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCandidateSelection.ProtoReflect.Descriptor instead.
func (*AccountCandidateSelection) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{11}
}

func (x *AccountCandidateSelection) GetRef() *AccountCandidateSelectionRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *AccountCandidateSelection) GetIndexSnapshotId() string {
	if x != nil {
		return x.IndexSnapshotId
	}
	return ""
}

func (x *AccountCandidateSelection) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *AccountCandidateSelection) GetGenesisHash() string {
	if x != nil {
		return x.GenesisHash
	}
	return ""
}

func (x *AccountCandidateSelection) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AccountCandidateSelection) GetRange() *BlockRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *AccountCandidateSelection) GetEvidenceProfile() string {
	if x != nil {
		return x.EvidenceProfile
	}
	return ""
}

func (x *AccountCandidateSelection) GetProfileHash() string {
	if x != nil {
		return x.ProfileHash
	}
	return ""
}

func (x *AccountCandidateSelection) GetCandidates() []*CandidateLocator {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type GetAccountSelectionResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Selection     *AccountCandidateSelection `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountSelectionResponse) Reset() {
	*x = GetAccountSelectionResponse{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSelectionResponse) ProtoMessage() {}

func (x *GetAccountSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSelectionResponse.ProtoReflect.Descriptor instead.
func (*GetAccountSelectionResponse) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{12}
}

func (x *GetAccountSelectionResponse) GetSelection() *AccountCandidateSelection {
	if x != nil {
		return x.Selection
	}
	return nil
}

type JitAccountInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	OwnershipFrom *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ownership_from,json=ownershipFrom,proto3" json:"ownership_from,omitempty"`
	OwnershipTo   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ownership_to,json=ownershipTo,proto3" json:"ownership_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JitAccountInput) Reset() {
	*x = JitAccountInput{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JitAccountInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JitAccountInput) ProtoMessage() {}

func (x *JitAccountInput) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JitAccountInput.ProtoReflect.Descriptor instead.
func (*JitAccountInput) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{13}
}

func (x *JitAccountInput) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *JitAccountInput) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *JitAccountInput) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *JitAccountInput) GetOwnershipFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.OwnershipFrom
	}
	return nil
}

func (x *JitAccountInput) GetOwnershipTo() *timestamppb.Timestamp {
	if x != nil {
		return x.OwnershipTo
	}
	return nil
}

type CandidateSelectionBinding struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	AccountId     string                        `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Selection     *AccountCandidateSelectionRef `protobuf:"bytes,2,opt,name=selection,proto3" json:"selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateSelectionBinding) Reset() {
	*x = CandidateSelectionBinding{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateSelectionBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateSelectionBinding) ProtoMessage() {}

func (x *CandidateSelectionBinding) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateSelectionBinding.ProtoReflect.Descriptor instead.
func (*CandidateSelectionBinding) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{14}
}

func (x *CandidateSelectionBinding) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CandidateSelectionBinding) GetSelection() *AccountCandidateSelectionRef {
	if x != nil {
		return x.Selection
	}
	return nil
}

type StartJitRunRequest struct {
	state               protoimpl.MessageState       `protogen:"open.v1"`
	GenerationId        string                       `protobuf:"bytes,1,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	SubjectId           string                       `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	IndexSnapshotId     string                       `protobuf:"bytes,3,opt,name=index_snapshot_id,json=indexSnapshotId,proto3" json:"index_snapshot_id,omitempty"`
	EvidenceProfile     string                       `protobuf:"bytes,4,opt,name=evidence_profile,json=evidenceProfile,proto3" json:"evidence_profile,omitempty"`
	Accounts            []*JitAccountInput           `protobuf:"bytes,5,rep,name=accounts,proto3" json:"accounts,omitempty"`
	CandidateSelections []*CandidateSelectionBinding `protobuf:"bytes,6,rep,name=candidate_selections,json=candidateSelections,proto3" json:"candidate_selections,omitempty"`
	RetryOfRunId        string                       `protobuf:"bytes,7,opt,name=retry_of_run_id,json=retryOfRunId,proto3" json:"retry_of_run_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StartJitRunRequest) Reset() {
	*x = StartJitRunRequest{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJitRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJitRunRequest) ProtoMessage() {}

func (x *StartJitRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJitRunRequest.ProtoReflect.Descriptor instead.
func (*StartJitRunRequest) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{15}
}

func (x *StartJitRunRequest) GetGenerationId() string {
	if x != nil {
		return x.GenerationId
	}
	return ""
}

func (x *StartJitRunRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *StartJitRunRequest) GetIndexSnapshotId() string {
	if x != nil {
		return x.IndexSnapshotId
	}
	return ""
}

func (x *StartJitRunRequest) GetEvidenceProfile() string {
	if x != nil {
		return x.EvidenceProfile
	}
	return ""
}

func (x *StartJitRunRequest) GetAccounts() []*JitAccountInput {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *StartJitRunRequest) GetCandidateSelections() []*CandidateSelectionBinding {
	if x != nil {
		return x.CandidateSelections
	}
	return nil
}

func (x *StartJitRunRequest) GetRetryOfRunId() string {
	if x != nil {
		return x.RetryOfRunId
	}
	return ""
}

type StartJitRunAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	RunRevision   uint64                 `protobuf:"varint,2,opt,name=run_revision,json=runRevision,proto3" json:"run_revision,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJitRunAccepted) Reset() {
	*x = StartJitRunAccepted{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJitRunAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJitRunAccepted) ProtoMessage() {}

func (x *StartJitRunAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJitRunAccepted.ProtoReflect.Descriptor instead.
func (*StartJitRunAccepted) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{16}
}

func (x *StartJitRunAccepted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartJitRunAccepted) GetRunRevision() uint64 {
	if x != nil {
		return x.RunRevision
	}
	return 0
}

func (x *StartJitRunAccepted) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type StartJitRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      *StartJitRunAccepted   `protobuf:"bytes,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJitRunResponse) Reset() {
	*x = StartJitRunResponse{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJitRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJitRunResponse) ProtoMessage() {}

func (x *StartJitRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJitRunResponse.ProtoReflect.Descriptor instead.
func (*StartJitRunResponse) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{17}
}

func (x *StartJitRunResponse) GetAccepted() *StartJitRunAccepted {
	if x != nil {
		return x.Accepted
	}
	return nil
}

type GetJitRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJitRunRequest) Reset() {
	*x = GetJitRunRequest{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJitRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJitRunRequest) ProtoMessage() {}

func (x *GetJitRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJitRunRequest.ProtoReflect.Descriptor instead.
func (*GetJitRunRequest) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{18}
}

func (x *GetJitRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type SchemaPin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	ModuleDigest  string                 `protobuf:"bytes,3,opt,name=module_digest,json=moduleDigest,proto3" json:"module_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaPin) Reset() {
	*x = SchemaPin{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaPin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaPin) ProtoMessage() {}

func (x *SchemaPin) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaPin.ProtoReflect.Descriptor instead.
func (*SchemaPin) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{19}
}

func (x *SchemaPin) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *SchemaPin) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *SchemaPin) GetModuleDigest() string {
	if x != nil {
		return x.ModuleDigest
	}
	return ""
}

type RuntimeConfigPin struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Digest              string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	ProviderSetRevision string                 `protobuf:"bytes,2,opt,name=provider_set_revision,json=providerSetRevision,proto3" json:"provider_set_revision,omitempty"`
	LoadedAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=loaded_at,json=loadedAt,proto3" json:"loaded_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RuntimeConfigPin) Reset() {
	*x = RuntimeConfigPin{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeConfigPin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeConfigPin) ProtoMessage() {}

func (x *RuntimeConfigPin) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeConfigPin.ProtoReflect.Descriptor instead.
func (*RuntimeConfigPin) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{20}
}

func (x *RuntimeConfigPin) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *RuntimeConfigPin) GetProviderSetRevision() string {
	if x != nil {
		return x.ProviderSetRevision
	}
	return ""
}

func (x *RuntimeConfigPin) GetLoadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LoadedAt
	}
	return nil
}

type JitProgress struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LogicalCandidates      uint64                 `protobuf:"varint,1,opt,name=logical_candidates,json=logicalCandidates,proto3" json:"logical_candidates,omitempty"`
	CandidatesTerminal     uint64                 `protobuf:"varint,2,opt,name=candidates_terminal,json=candidatesTerminal,proto3" json:"candidates_terminal,omitempty"`
	ExecutionsAvailable    uint64                 `protobuf:"varint,3,opt,name=executions_available,json=executionsAvailable,proto3" json:"executions_available,omitempty"`
	ObservationsNormalized uint64                 `protobuf:"varint,4,opt,name=observations_normalized,json=observationsNormalized,proto3" json:"observations_normalized,omitempty"`
	EvidenceUnavailable    uint64                 `protobuf:"varint,5,opt,name=evidence_unavailable,json=evidenceUnavailable,proto3" json:"evidence_unavailable,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *JitProgress) Reset() {
	*x = JitProgress{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JitProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JitProgress) ProtoMessage() {}

func (x *JitProgress) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JitProgress.ProtoReflect.Descriptor instead.
func (*JitProgress) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{21}
}

func (x *JitProgress) GetLogicalCandidates() uint64 {
	if x != nil {
		return x.LogicalCandidates
	}
	return 0
}

func (x *JitProgress) GetCandidatesTerminal() uint64 {
	if x != nil {
		return x.CandidatesTerminal
	}
	return 0
}

func (x *JitProgress) GetExecutionsAvailable() uint64 {
	if x != nil {
		return x.ExecutionsAvailable
	}
	return 0
}

func (x *JitProgress) GetObservationsNormalized() uint64 {
	if x != nil {
		return x.ObservationsNormalized
	}
	return 0
}

func (x *JitProgress) GetEvidenceUnavailable() uint64 {
	if x != nil {
		return x.EvidenceUnavailable
	}
	return 0
}

type JitRunResultEnvelope struct {
	state                      protoimpl.MessageState       `protogen:"open.v1"`
	RunId                      string                       `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	RunRevision                uint64                       `protobuf:"varint,2,opt,name=run_revision,json=runRevision,proto3" json:"run_revision,omitempty"`
	Status                     string                       `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	IndexSnapshotId            string                       `protobuf:"bytes,4,opt,name=index_snapshot_id,json=indexSnapshotId,proto3" json:"index_snapshot_id,omitempty"`
	CandidateSelections        []*CandidateSelectionBinding `protobuf:"bytes,5,rep,name=candidate_selections,json=candidateSelections,proto3" json:"candidate_selections,omitempty"`
	Progress                   *JitProgress                 `protobuf:"bytes,6,opt,name=progress,proto3" json:"progress,omitempty"`
	ChainEvidenceBundleId      string                       `protobuf:"bytes,7,opt,name=chain_evidence_bundle_id,json=chainEvidenceBundleId,proto3" json:"chain_evidence_bundle_id,omitempty"`
	SubjectEvidenceFragmentId  string                       `protobuf:"bytes,8,opt,name=subject_evidence_fragment_id,json=subjectEvidenceFragmentId,proto3" json:"subject_evidence_fragment_id,omitempty"`
	CandidateOutcomeArtifact   *ArtifactRef                 `protobuf:"bytes,9,opt,name=candidate_outcome_artifact,json=candidateOutcomeArtifact,proto3" json:"candidate_outcome_artifact,omitempty"`
	LimitationArtifact         *ArtifactRef                 `protobuf:"bytes,10,opt,name=limitation_artifact,json=limitationArtifact,proto3" json:"limitation_artifact,omitempty"`
	ResultDigest               string                       `protobuf:"bytes,11,opt,name=result_digest,json=resultDigest,proto3" json:"result_digest,omitempty"`
	SchemaPin                  *SchemaPin                   `protobuf:"bytes,12,opt,name=schema_pin,json=schemaPin,proto3" json:"schema_pin,omitempty"`
	RetryOfRunId               string                       `protobuf:"bytes,13,opt,name=retry_of_run_id,json=retryOfRunId,proto3" json:"retry_of_run_id,omitempty"`
	SupersedesRunId            string                       `protobuf:"bytes,14,opt,name=supersedes_run_id,json=supersedesRunId,proto3" json:"supersedes_run_id,omitempty"`
	ChainEvidenceArtifact      *ArtifactRef                 `protobuf:"bytes,15,opt,name=chain_evidence_artifact,json=chainEvidenceArtifact,proto3" json:"chain_evidence_artifact,omitempty"`
	SubjectEvidenceArtifact    *ArtifactRef                 `protobuf:"bytes,16,opt,name=subject_evidence_artifact,json=subjectEvidenceArtifact,proto3" json:"subject_evidence_artifact,omitempty"`
	RuntimeConfigPin           *RuntimeConfigPin            `protobuf:"bytes,17,opt,name=runtime_config_pin,json=runtimeConfigPin,proto3" json:"runtime_config_pin,omitempty"`
	ExecutionEvidenceArtifacts []*ArtifactRef               `protobuf:"bytes,18,rep,name=execution_evidence_artifacts,json=executionEvidenceArtifacts,proto3" json:"execution_evidence_artifacts,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *JitRunResultEnvelope) Reset() {
	*x = JitRunResultEnvelope{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JitRunResultEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JitRunResultEnvelope) ProtoMessage() {}

func (x *JitRunResultEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JitRunResultEnvelope.ProtoReflect.Descriptor instead.
func (*JitRunResultEnvelope) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{22}
}

func (x *JitRunResultEnvelope) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *JitRunResultEnvelope) GetRunRevision() uint64 {
	if x != nil {
		return x.RunRevision
	}
	return 0
}

func (x *JitRunResultEnvelope) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JitRunResultEnvelope) GetIndexSnapshotId() string {
	if x != nil {
		return x.IndexSnapshotId
	}
	return ""
}

func (x *JitRunResultEnvelope) GetCandidateSelections() []*CandidateSelectionBinding {
	if x != nil {
		return x.CandidateSelections
	}
	return nil
}

func (x *JitRunResultEnvelope) GetProgress() *JitProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *JitRunResultEnvelope) GetChainEvidenceBundleId() string {
	if x != nil {
		return x.ChainEvidenceBundleId
	}
	return ""
}

func (x *JitRunResultEnvelope) GetSubjectEvidenceFragmentId() string {
	if x != nil {
		return x.SubjectEvidenceFragmentId
	}
	return ""
}

func (x *JitRunResultEnvelope) GetCandidateOutcomeArtifact() *ArtifactRef {
	if x != nil {
		return x.CandidateOutcomeArtifact
	}
	return nil
}

func (x *JitRunResultEnvelope) GetLimitationArtifact() *ArtifactRef {
	if x != nil {
		return x.LimitationArtifact
	}
	return nil
}

func (x *JitRunResultEnvelope) GetResultDigest() string {
	if x != nil {
		return x.ResultDigest
	}
	return ""
}

func (x *JitRunResultEnvelope) GetSchemaPin() *SchemaPin {
	if x != nil {
		return x.SchemaPin
	}
	return nil
}

func (x *JitRunResultEnvelope) GetRetryOfRunId() string {
	if x != nil {
		return x.RetryOfRunId
	}
	return ""
}

func (x *JitRunResultEnvelope) GetSupersedesRunId() string {
	if x != nil {
		return x.SupersedesRunId
	}
	return ""
}

func (x *JitRunResultEnvelope) GetChainEvidenceArtifact() *ArtifactRef {
	if x != nil {
		return x.ChainEvidenceArtifact
	}
	return nil
}

func (x *JitRunResultEnvelope) GetSubjectEvidenceArtifact() *ArtifactRef {
	if x != nil {
		return x.SubjectEvidenceArtifact
	}
	return nil
}

func (x *JitRunResultEnvelope) GetRuntimeConfigPin() *RuntimeConfigPin {
	if x != nil {
		return x.RuntimeConfigPin
	}
	return nil
}

func (x *JitRunResultEnvelope) GetExecutionEvidenceArtifacts() []*ArtifactRef {
	if x != nil {
		return x.ExecutionEvidenceArtifacts
	}
	return nil
}

type GetJitRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *JitRunResultEnvelope  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJitRunResponse) Reset() {
	*x = GetJitRunResponse{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJitRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJitRunResponse) ProtoMessage() {}

func (x *GetJitRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJitRunResponse.ProtoReflect.Descriptor instead.
func (*GetJitRunResponse) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{23}
}

func (x *GetJitRunResponse) GetResult() *JitRunResultEnvelope {
	if x != nil {
		return x.Result
	}
	return nil
}

type CandidateOutcome struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CandidateId        string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	AccountId          string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Locator            *CandidateLocator      `protobuf:"bytes,3,opt,name=locator,proto3" json:"locator,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ReasonCode         string                 `protobuf:"bytes,5,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	HitIds             []string               `protobuf:"bytes,6,rep,name=hit_ids,json=hitIds,proto3" json:"hit_ids,omitempty"`
	ObservationIds     []string               `protobuf:"bytes,7,rep,name=observation_ids,json=observationIds,proto3" json:"observation_ids,omitempty"`
	MatchBitOutcomes   []*MatchBitOutcome     `protobuf:"bytes,8,rep,name=match_bit_outcomes,json=matchBitOutcomes,proto3" json:"match_bit_outcomes,omitempty"`
	EvidencePartStates []*EvidencePartState   `protobuf:"bytes,9,rep,name=evidence_part_states,json=evidencePartStates,proto3" json:"evidence_part_states,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CandidateOutcome) Reset() {
	*x = CandidateOutcome{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateOutcome) ProtoMessage() {}

func (x *CandidateOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateOutcome.ProtoReflect.Descriptor instead.
func (*CandidateOutcome) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{24}
}

func (x *CandidateOutcome) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *CandidateOutcome) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CandidateOutcome) GetLocator() *CandidateLocator {
	if x != nil {
		return x.Locator
	}
	return nil
}

func (x *CandidateOutcome) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CandidateOutcome) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CandidateOutcome) GetHitIds() []string {
	if x != nil {
		return x.HitIds
	}
	return nil
}

func (x *CandidateOutcome) GetObservationIds() []string {
	if x != nil {
		return x.ObservationIds
	}
	return nil
}

func (x *CandidateOutcome) GetMatchBitOutcomes() []*MatchBitOutcome {
	if x != nil {
		return x.MatchBitOutcomes
	}
	return nil
}

func (x *CandidateOutcome) GetEvidencePartStates() []*EvidencePartState {
	if x != nil {
		return x.EvidencePartStates
	}
	return nil
}

type MatchBitOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchBit      uint32                 `protobuf:"varint,1,opt,name=match_bit,json=matchBit,proto3" json:"match_bit,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,3,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	HitIds        []string               `protobuf:"bytes,4,rep,name=hit_ids,json=hitIds,proto3" json:"hit_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchBitOutcome) Reset() {
	*x = MatchBitOutcome{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchBitOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchBitOutcome) ProtoMessage() {}

func (x *MatchBitOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchBitOutcome.ProtoReflect.Descriptor instead.
func (*MatchBitOutcome) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{25}
}

func (x *MatchBitOutcome) GetMatchBit() uint32 {
	if x != nil {
		return x.MatchBit
	}
	return 0
}

func (x *MatchBitOutcome) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatchBitOutcome) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *MatchBitOutcome) GetHitIds() []string {
	if x != nil {
		return x.HitIds
	}
	return nil
}

type EvidencePartState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EvidencePart  string                 `protobuf:"bytes,1,opt,name=evidence_part,json=evidencePart,proto3" json:"evidence_part,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidencePartState) Reset() {
	*x = EvidencePartState{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidencePartState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidencePartState) ProtoMessage() {}

func (x *EvidencePartState) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidencePartState.ProtoReflect.Descriptor instead.
func (*EvidencePartState) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{26}
}

func (x *EvidencePartState) GetEvidencePart() string {
	if x != nil {
		return x.EvidencePart
	}
	return ""
}

func (x *EvidencePartState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ListCandidateOutcomesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCandidateOutcomesRequest) Reset() {
	*x = ListCandidateOutcomesRequest{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCandidateOutcomesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidateOutcomesRequest) ProtoMessage() {}

func (x *ListCandidateOutcomesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidateOutcomesRequest.ProtoReflect.Descriptor instead.
func (*ListCandidateOutcomesRequest) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{27}
}

func (x *ListCandidateOutcomesRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ListCandidateOutcomesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCandidateOutcomesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCandidateOutcomesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcomes      []*CandidateOutcome    `protobuf:"bytes,1,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCandidateOutcomesResponse) Reset() {
	*x = ListCandidateOutcomesResponse{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCandidateOutcomesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidateOutcomesResponse) ProtoMessage() {}

func (x *ListCandidateOutcomesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidateOutcomesResponse.ProtoReflect.Descriptor instead.
func (*ListCandidateOutcomesResponse) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{28}
}

func (x *ListCandidateOutcomesResponse) GetOutcomes() []*CandidateOutcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

func (x *ListCandidateOutcomesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type RetryJitRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryJitRunRequest) Reset() {
	*x = RetryJitRunRequest{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryJitRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryJitRunRequest) ProtoMessage() {}

func (x *RetryJitRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryJitRunRequest.ProtoReflect.Descriptor instead.
func (*RetryJitRunRequest) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{29}
}

func (x *RetryJitRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RetryJitRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      *StartJitRunAccepted   `protobuf:"bytes,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryJitRunResponse) Reset() {
	*x = RetryJitRunResponse{}
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryJitRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryJitRunResponse) ProtoMessage() {}

func (x *RetryJitRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_giwa_jit_v1_jit_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryJitRunResponse.ProtoReflect.Descriptor instead.
func (*RetryJitRunResponse) Descriptor() ([]byte, []int) {
	return file_giwa_jit_v1_jit_proto_rawDescGZIP(), []int{30}
}

func (x *RetryJitRunResponse) GetAccepted() *StartJitRunAccepted {
	if x != nil {
		return x.Accepted
	}
	return nil
}

var File_giwa_jit_v1_jit_proto protoreflect.FileDescriptor

const file_giwa_jit_v1_jit_proto_rawDesc = "" +
	"\n" +
	"\x15giwa/jit/v1/jit.proto\x12\vgiwa.jit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"?\n" +
	"\tHashValue\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"b\n" +
	"\vArtifactRef\x129\n" +
	"\fcontent_hash\x18\x01 \x01(\v2\x16.giwa.jit.v1.HashValueR\vcontentHash\x12\x18\n" +
	"\alocator\x18\x02 \x01(\tR\alocator\"\x87\x01\n" +
	"\bBlockRef\x12!\n" +
	"\fblock_number\x18\x01 \x01(\tR\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\tR\tblockHash\x129\n" +
	"\n" +
	"block_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tblockTime\"F\n" +
	"\n" +
	"BlockRange\x12\x1d\n" +
	"\n" +
	"from_block\x18\x01 \x01(\tR\tfromBlock\x12\x19\n" +
	"\bto_block\x18\x02 \x01(\tR\atoBlock\"\x83\x01\n" +
	"\x12TransactionLocator\x12!\n" +
	"\fblock_number\x18\x01 \x01(\tR\vblockNumber\x12+\n" +
	"\x11transaction_index\x18\x02 \x01(\rR\x10transactionIndex\x12\x1d\n" +
	"\n" +
	"match_bits\x18\x03 \x01(\rR\tmatchBits\"\x93\x01\n" +
	"\x11BlockEventLocator\x12!\n" +
	"\fblock_number\x18\x01 \x01(\tR\vblockNumber\x12:\n" +
	"\n" +
	"event_kind\x18\x02 \x01(\x0e2\x1b.giwa.jit.v1.BlockEventKindR\teventKind\x12\x1f\n" +
	"\vevent_index\x18\x03 \x01(\x04R\n" +
	"eventIndex\"\xa6\x01\n" +
	"\x10CandidateLocator\x12C\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1f.giwa.jit.v1.TransactionLocatorH\x00R\vtransaction\x12A\n" +
	"\vblock_event\x18\x02 \x01(\v2\x1e.giwa.jit.v1.BlockEventLocatorH\x00R\n" +
	"blockEventB\n" +
	"\n" +
	"\bposition\"\xc6\x02\n" +
	"\"MaterializeAccountSelectionRequest\x12*\n" +
	"\x11index_snapshot_id\x18\x01 \x01(\tR\x0findexSnapshotId\x12\x1f\n" +
	"\vchain_store\x18\x02 \x01(\tR\n" +
	"chainStore\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\tR\achainId\x12!\n" +
	"\fgenesis_hash\x18\x04 \x01(\tR\vgenesisHash\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12-\n" +
	"\x05range\x18\x06 \x01(\v2\x17.giwa.jit.v1.BlockRangeR\x05range\x12)\n" +
	"\x10evidence_profile\x18\a \x01(\tR\x0fevidenceProfile\x12!\n" +
	"\fprofile_hash\x18\b \x01(\tR\vprofileHash\"\xed\x01\n" +
	"\x1cAccountCandidateSelectionRef\x12!\n" +
	"\fselection_id\x18\x01 \x01(\tR\vselectionId\x12)\n" +
	"\x10selection_digest\x18\x02 \x01(\tR\x0fselectionDigest\x126\n" +
	"\x17logical_candidate_count\x18\x03 \x01(\x04R\x15logicalCandidateCount\x12G\n" +
	"\x12selection_artifact\x18\x04 \x01(\v2\x18.giwa.jit.v1.ArtifactRefR\x11selectionArtifact\"n\n" +
	"#MaterializeAccountSelectionResponse\x12G\n" +
	"\tselection\x18\x01 \x01(\v2).giwa.jit.v1.AccountCandidateSelectionRefR\tselection\"h\n" +
	"\x1aGetAccountSelectionRequest\x12!\n" +
	"\fselection_id\x18\x01 \x01(\tR\vselectionId\x12'\n" +
	"\x0fexpected_digest\x18\x02 \x01(\tR\x0eexpectedDigest\"\x98\x03\n" +
	"\x19AccountCandidateSelection\x12;\n" +
	"\x03ref\x18\x01 \x01(\v2).giwa.jit.v1.AccountCandidateSelectionRefR\x03ref\x12*\n" +
	"\x11index_snapshot_id\x18\x02 \x01(\tR\x0findexSnapshotId\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\tR\achainId\x12!\n" +
	"\fgenesis_hash\x18\x04 \x01(\tR\vgenesisHash\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12-\n" +
	"\x05range\x18\x06 \x01(\v2\x17.giwa.jit.v1.BlockRangeR\x05range\x12)\n" +
	"\x10evidence_profile\x18\a \x01(\tR\x0fevidenceProfile\x12!\n" +
	"\fprofile_hash\x18\b \x01(\tR\vprofileHash\x12=\n" +
	"\n" +
	"candidates\x18\t \x03(\v2\x1d.giwa.jit.v1.CandidateLocatorR\n" +
	"candidates\"c\n" +
	"\x1bGetAccountSelectionResponse\x12D\n" +
	"\tselection\x18\x01 \x01(\v2&.giwa.jit.v1.AccountCandidateSelectionR\tselection\"\xe7\x01\n" +
	"\x0fJitAccountInput\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12A\n" +
	"\x0eownership_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rownershipFrom\x12=\n" +
	"\fownership_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vownershipTo\"\x83\x01\n" +
	"\x19CandidateSelectionBinding\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12G\n" +
	"\tselection\x18\x02 \x01(\v2).giwa.jit.v1.AccountCandidateSelectionRefR\tselection\"\xeb\x02\n" +
	"\x12StartJitRunRequest\x12#\n" +
	"\rgeneration_id\x18\x01 \x01(\tR\fgenerationId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12*\n" +
	"\x11index_snapshot_id\x18\x03 \x01(\tR\x0findexSnapshotId\x12)\n" +
	"\x10evidence_profile\x18\x04 \x01(\tR\x0fevidenceProfile\x128\n" +
	"\baccounts\x18\x05 \x03(\v2\x1c.giwa.jit.v1.JitAccountInputR\baccounts\x12Y\n" +
	"\x14candidate_selections\x18\x06 \x03(\v2&.giwa.jit.v1.CandidateSelectionBindingR\x13candidateSelections\x12%\n" +
	"\x0fretry_of_run_id\x18\a \x01(\tR\fretryOfRunId\"e\n" +
	"\x13StartJitRunAccepted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12!\n" +
	"\frun_revision\x18\x02 \x01(\x04R\vrunRevision\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"S\n" +
	"\x13StartJitRunResponse\x12<\n" +
	"\baccepted\x18\x01 \x01(\v2 .giwa.jit.v1.StartJitRunAcceptedR\baccepted\")\n" +
	"\x10GetJitRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"h\n" +
	"\tSchemaPin\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12#\n" +
	"\rmodule_digest\x18\x03 \x01(\tR\fmoduleDigest\"\x97\x01\n" +
	"\x10RuntimeConfigPin\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x122\n" +
	"\x15provider_set_revision\x18\x02 \x01(\tR\x13providerSetRevision\x127\n" +
	"\tloaded_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bloadedAt\"\x8c\x02\n" +
	"\vJitProgress\x12-\n" +
	"\x12logical_candidates\x18\x01 \x01(\x04R\x11logicalCandidates\x12/\n" +
	"\x13candidates_terminal\x18\x02 \x01(\x04R\x12candidatesTerminal\x121\n" +
	"\x14executions_available\x18\x03 \x01(\x04R\x13executionsAvailable\x127\n" +
	"\x17observations_normalized\x18\x04 \x01(\x04R\x16observationsNormalized\x121\n" +
	"\x14evidence_unavailable\x18\x05 \x01(\x04R\x13evidenceUnavailable\"\xc2\b\n" +
	"\x14JitRunResultEnvelope\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12!\n" +
	"\frun_revision\x18\x02 \x01(\x04R\vrunRevision\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12*\n" +
	"\x11index_snapshot_id\x18\x04 \x01(\tR\x0findexSnapshotId\x12Y\n" +
	"\x14candidate_selections\x18\x05 \x03(\v2&.giwa.jit.v1.CandidateSelectionBindingR\x13candidateSelections\x124\n" +
	"\bprogress\x18\x06 \x01(\v2\x18.giwa.jit.v1.JitProgressR\bprogress\x127\n" +
	"\x18chain_evidence_bundle_id\x18\a \x01(\tR\x15chainEvidenceBundleId\x12?\n" +
	"\x1csubject_evidence_fragment_id\x18\b \x01(\tR\x19subjectEvidenceFragmentId\x12V\n" +
	"\x1acandidate_outcome_artifact\x18\t \x01(\v2\x18.giwa.jit.v1.ArtifactRefR\x18candidateOutcomeArtifact\x12I\n" +
	"\x13limitation_artifact\x18\n" +
	" \x01(\v2\x18.giwa.jit.v1.ArtifactRefR\x12limitationArtifact\x12#\n" +
	"\rresult_digest\x18\v \x01(\tR\fresultDigest\x125\n" +
	"\n" +
	"schema_pin\x18\f \x01(\v2\x16.giwa.jit.v1.SchemaPinR\tschemaPin\x12%\n" +
	"\x0fretry_of_run_id\x18\r \x01(\tR\fretryOfRunId\x12*\n" +
	"\x11supersedes_run_id\x18\x0e \x01(\tR\x0fsupersedesRunId\x12P\n" +
	"\x17chain_evidence_artifact\x18\x0f \x01(\v2\x18.giwa.jit.v1.ArtifactRefR\x15chainEvidenceArtifact\x12T\n" +
	"\x19subject_evidence_artifact\x18\x10 \x01(\v2\x18.giwa.jit.v1.ArtifactRefR\x17subjectEvidenceArtifact\x12K\n" +
	"\x12runtime_config_pin\x18\x11 \x01(\v2\x1d.giwa.jit.v1.RuntimeConfigPinR\x10runtimeConfigPin\x12Z\n" +
	"\x1cexecution_evidence_artifacts\x18\x12 \x03(\v2\x18.giwa.jit.v1.ArtifactRefR\x1aexecutionEvidenceArtifacts\"N\n" +
	"\x11GetJitRunResponse\x129\n" +
	"\x06result\x18\x01 \x01(\v2!.giwa.jit.v1.JitRunResultEnvelopeR\x06result\"\xa6\x03\n" +
	"\x10CandidateOutcome\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x127\n" +
	"\alocator\x18\x03 \x01(\v2\x1d.giwa.jit.v1.CandidateLocatorR\alocator\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vreason_code\x18\x05 \x01(\tR\n" +
	"reasonCode\x12\x17\n" +
	"\ahit_ids\x18\x06 \x03(\tR\x06hitIds\x12'\n" +
	"\x0fobservation_ids\x18\a \x03(\tR\x0eobservationIds\x12J\n" +
	"\x12match_bit_outcomes\x18\b \x03(\v2\x1c.giwa.jit.v1.MatchBitOutcomeR\x10matchBitOutcomes\x12P\n" +
	"\x14evidence_part_states\x18\t \x03(\v2\x1e.giwa.jit.v1.EvidencePartStateR\x12evidencePartStates\"\x80\x01\n" +
	"\x0fMatchBitOutcome\x12\x1b\n" +
	"\tmatch_bit\x18\x01 \x01(\rR\bmatchBit\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vreason_code\x18\x03 \x01(\tR\n" +
	"reasonCode\x12\x17\n" +
	"\ahit_ids\x18\x04 \x03(\tR\x06hitIds\"N\n" +
	"\x11EvidencePartState\x12#\n" +
	"\revidence_part\x18\x01 \x01(\tR\fevidencePart\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"q\n" +
	"\x1cListCandidateOutcomesRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x82\x01\n" +
	"\x1dListCandidateOutcomesResponse\x129\n" +
	"\boutcomes\x18\x01 \x03(\v2\x1d.giwa.jit.v1.CandidateOutcomeR\boutcomes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"+\n" +
	"\x12RetryJitRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"S\n" +
	"\x13RetryJitRunResponse\x12<\n" +
	"\baccepted\x18\x01 \x01(\v2 .giwa.jit.v1.StartJitRunAcceptedR\baccepted*Z\n" +
	"\x0eBlockEventKind\x12 \n" +
	"\x1cBLOCK_EVENT_KIND_UNSPECIFIED\x10\x00\x12&\n" +
	"\"BLOCK_EVENT_KIND_BEACON_WITHDRAWAL\x10\x012\x9a\x01\n" +
	"\x15CandidateQueryService\x12\x80\x01\n" +
	"\x1bMaterializeAccountSelection\x12/.giwa.jit.v1.MaterializeAccountSelectionRequest\x1a0.giwa.jit.v1.MaterializeAccountSelectionResponse2\xf2\x02\n" +
	"\x10JitEngineService\x12P\n" +
	"\vStartJitRun\x12\x1f.giwa.jit.v1.StartJitRunRequest\x1a .giwa.jit.v1.StartJitRunResponse\x12J\n" +
	"\tGetJitRun\x12\x1d.giwa.jit.v1.GetJitRunRequest\x1a\x1e.giwa.jit.v1.GetJitRunResponse\x12n\n" +
	"\x15ListCandidateOutcomes\x12).giwa.jit.v1.ListCandidateOutcomesRequest\x1a*.giwa.jit.v1.ListCandidateOutcomesResponse\x12P\n" +
	"\vRetryJitRun\x12\x1f.giwa.jit.v1.RetryJitRunRequest\x1a .giwa.jit.v1.RetryJitRunResponseBEZCgithub.com/BackwardLabs/daejang-jit-engine/gen/go/giwa/jit/v1;jitv1b\x06proto3"

var (
	file_giwa_jit_v1_jit_proto_rawDescOnce sync.Once
	file_giwa_jit_v1_jit_proto_rawDescData []byte
)

func file_giwa_jit_v1_jit_proto_rawDescGZIP() []byte {
	file_giwa_jit_v1_jit_proto_rawDescOnce.Do(func() {
		file_giwa_jit_v1_jit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_giwa_jit_v1_jit_proto_rawDesc), len(file_giwa_jit_v1_jit_proto_rawDesc)))
	})
	return file_giwa_jit_v1_jit_proto_rawDescData
}

var file_giwa_jit_v1_jit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_giwa_jit_v1_jit_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_giwa_jit_v1_jit_proto_goTypes = []any{
	(BlockEventKind)(0),                         // 0: giwa.jit.v1.BlockEventKind
	(*HashValue)(nil),                           // 1: giwa.jit.v1.HashValue
	(*ArtifactRef)(nil),                         // 2: giwa.jit.v1.ArtifactRef
	(*BlockRef)(nil),                            // 3: giwa.jit.v1.BlockRef
	(*BlockRange)(nil),                          // 4: giwa.jit.v1.BlockRange
	(*TransactionLocator)(nil),                  // 5: giwa.jit.v1.TransactionLocator
	(*BlockEventLocator)(nil),                   // 6: giwa.jit.v1.BlockEventLocator
	(*CandidateLocator)(nil),                    // 7: giwa.jit.v1.CandidateLocator
	(*MaterializeAccountSelectionRequest)(nil),  // 8: giwa.jit.v1.MaterializeAccountSelectionRequest
	(*AccountCandidateSelectionRef)(nil),        // 9: giwa.jit.v1.AccountCandidateSelectionRef
	(*MaterializeAccountSelectionResponse)(nil), // 10: giwa.jit.v1.MaterializeAccountSelectionResponse
	(*GetAccountSelectionRequest)(nil),          // 11: giwa.jit.v1.GetAccountSelectionRequest
	(*AccountCandidateSelection)(nil),           // 12: giwa.jit.v1.AccountCandidateSelection
	(*GetAccountSelectionResponse)(nil),         // 13: giwa.jit.v1.GetAccountSelectionResponse
	(*JitAccountInput)(nil),                     // 14: giwa.jit.v1.JitAccountInput
	(*CandidateSelectionBinding)(nil),           // 15: giwa.jit.v1.CandidateSelectionBinding
	(*StartJitRunRequest)(nil),                  // 16: giwa.jit.v1.StartJitRunRequest
	(*StartJitRunAccepted)(nil),                 // 17: giwa.jit.v1.StartJitRunAccepted
	(*StartJitRunResponse)(nil),                 // 18: giwa.jit.v1.StartJitRunResponse
	(*GetJitRunRequest)(nil),                    // 19: giwa.jit.v1.GetJitRunRequest
	(*SchemaPin)(nil),                           // 20: giwa.jit.v1.SchemaPin
	(*RuntimeConfigPin)(nil),                    // 21: giwa.jit.v1.RuntimeConfigPin
	(*JitProgress)(nil),                         // 22: giwa.jit.v1.JitProgress
	(*JitRunResultEnvelope)(nil),                // 23: giwa.jit.v1.JitRunResultEnvelope
	(*GetJitRunResponse)(nil),                   // 24: giwa.jit.v1.GetJitRunResponse
	(*CandidateOutcome)(nil),                    // 25: giwa.jit.v1.CandidateOutcome
	(*MatchBitOutcome)(nil),                     // 26: giwa.jit.v1.MatchBitOutcome
	(*EvidencePartState)(nil),                   // 27: giwa.jit.v1.EvidencePartState
	(*ListCandidateOutcomesRequest)(nil),        // 28: giwa.jit.v1.ListCandidateOutcomesRequest
	(*ListCandidateOutcomesResponse)(nil),       // 29: giwa.jit.v1.ListCandidateOutcomesResponse
	(*RetryJitRunRequest)(nil),                  // 30: giwa.jit.v1.RetryJitRunRequest
	(*RetryJitRunResponse)(nil),                 // 31: giwa.jit.v1.RetryJitRunResponse
	(*timestamppb.Timestamp)(nil),               // 32: google.protobuf.Timestamp
}
var file_giwa_jit_v1_jit_proto_depIdxs = []int32{
	1,  // 0: giwa.jit.v1.ArtifactRef.content_hash:type_name -> giwa.jit.v1.HashValue
	32, // 1: giwa.jit.v1.BlockRef.block_time:type_name -> google.protobuf.Timestamp
	0,  // 2: giwa.jit.v1.BlockEventLocator.event_kind:type_name -> giwa.jit.v1.BlockEventKind
	5,  // 3: giwa.jit.v1.CandidateLocator.transaction:type_name -> giwa.jit.v1.TransactionLocator
	6,  // 4: giwa.jit.v1.CandidateLocator.block_event:type_name -> giwa.jit.v1.BlockEventLocator
	4,  // 5: giwa.jit.v1.MaterializeAccountSelectionRequest.range:type_name -> giwa.jit.v1.BlockRange
	2,  // 6: giwa.jit.v1.AccountCandidateSelectionRef.selection_artifact:type_name -> giwa.jit.v1.ArtifactRef
	9,  // 7: giwa.jit.v1.MaterializeAccountSelectionResponse.selection:type_name -> giwa.jit.v1.AccountCandidateSelectionRef
	9,  // 8: giwa.jit.v1.AccountCandidateSelection.ref:type_name -> giwa.jit.v1.AccountCandidateSelectionRef
	4,  // 9: giwa.jit.v1.AccountCandidateSelection.range:type_name -> giwa.jit.v1.BlockRange
	7,  // 10: giwa.jit.v1.AccountCandidateSelection.candidates:type_name -> giwa.jit.v1.CandidateLocator
	12, // 11: giwa.jit.v1.GetAccountSelectionResponse.selection:type_name -> giwa.jit.v1.AccountCandidateSelection
	32, // 12: giwa.jit.v1.JitAccountInput.ownership_from:type_name -> google.protobuf.Timestamp
	32, // 13: giwa.jit.v1.JitAccountInput.ownership_to:type_name -> google.protobuf.Timestamp
	9,  // 14: giwa.jit.v1.CandidateSelectionBinding.selection:type_name -> giwa.jit.v1.AccountCandidateSelectionRef
	14, // 15: giwa.jit.v1.StartJitRunRequest.accounts:type_name -> giwa.jit.v1.JitAccountInput
	15, // 16: giwa.jit.v1.StartJitRunRequest.candidate_selections:type_name -> giwa.jit.v1.CandidateSelectionBinding
	17, // 17: giwa.jit.v1.StartJitRunResponse.accepted:type_name -> giwa.jit.v1.StartJitRunAccepted
	32, // 18: giwa.jit.v1.RuntimeConfigPin.loaded_at:type_name -> google.protobuf.Timestamp
	15, // 19: giwa.jit.v1.JitRunResultEnvelope.candidate_selections:type_name -> giwa.jit.v1.CandidateSelectionBinding
	22, // 20: giwa.jit.v1.JitRunResultEnvelope.progress:type_name -> giwa.jit.v1.JitProgress
	2,  // 21: giwa.jit.v1.JitRunResultEnvelope.candidate_outcome_artifact:type_name -> giwa.jit.v1.ArtifactRef
	2,  // 22: giwa.jit.v1.JitRunResultEnvelope.limitation_artifact:type_name -> giwa.jit.v1.ArtifactRef
	20, // 23: giwa.jit.v1.JitRunResultEnvelope.schema_pin:type_name -> giwa.jit.v1.SchemaPin
	2,  // 24: giwa.jit.v1.JitRunResultEnvelope.chain_evidence_artifact:type_name -> giwa.jit.v1.ArtifactRef
	2,  // 25: giwa.jit.v1.JitRunResultEnvelope.subject_evidence_artifact:type_name -> giwa.jit.v1.ArtifactRef
	21, // 26: giwa.jit.v1.JitRunResultEnvelope.runtime_config_pin:type_name -> giwa.jit.v1.RuntimeConfigPin
	2,  // 27: giwa.jit.v1.JitRunResultEnvelope.execution_evidence_artifacts:type_name -> giwa.jit.v1.ArtifactRef
	23, // 28: giwa.jit.v1.GetJitRunResponse.result:type_name -> giwa.jit.v1.JitRunResultEnvelope
	7,  // 29: giwa.jit.v1.CandidateOutcome.locator:type_name -> giwa.jit.v1.CandidateLocator
	26, // 30: giwa.jit.v1.CandidateOutcome.match_bit_outcomes:type_name -> giwa.jit.v1.MatchBitOutcome
	27, // 31: giwa.jit.v1.CandidateOutcome.evidence_part_states:type_name -> giwa.jit.v1.EvidencePartState
	25, // 32: giwa.jit.v1.ListCandidateOutcomesResponse.outcomes:type_name -> giwa.jit.v1.CandidateOutcome
	17, // 33: giwa.jit.v1.RetryJitRunResponse.accepted:type_name -> giwa.jit.v1.StartJitRunAccepted
	8,  // 34: giwa.jit.v1.CandidateQueryService.MaterializeAccountSelection:input_type -> giwa.jit.v1.MaterializeAccountSelectionRequest
	16, // 35: giwa.jit.v1.JitEngineService.StartJitRun:input_type -> giwa.jit.v1.StartJitRunRequest
	19, // 36: giwa.jit.v1.JitEngineService.GetJitRun:input_type -> giwa.jit.v1.GetJitRunRequest
	28, // 37: giwa.jit.v1.JitEngineService.ListCandidateOutcomes:input_type -> giwa.jit.v1.ListCandidateOutcomesRequest
	30, // 38: giwa.jit.v1.JitEngineService.RetryJitRun:input_type -> giwa.jit.v1.RetryJitRunRequest
	10, // 39: giwa.jit.v1.CandidateQueryService.MaterializeAccountSelection:output_type -> giwa.jit.v1.MaterializeAccountSelectionResponse
	18, // 40: giwa.jit.v1.JitEngineService.StartJitRun:output_type -> giwa.jit.v1.StartJitRunResponse
	24, // 41: giwa.jit.v1.JitEngineService.GetJitRun:output_type -> giwa.jit.v1.GetJitRunResponse
	29, // 42: giwa.jit.v1.JitEngineService.ListCandidateOutcomes:output_type -> giwa.jit.v1.ListCandidateOutcomesResponse
	31, // 43: giwa.jit.v1.JitEngineService.RetryJitRun:output_type -> giwa.jit.v1.RetryJitRunResponse
	39, // [39:44] is the sub-list for method output_type
	34, // [34:39] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_giwa_jit_v1_jit_proto_init() }
func file_giwa_jit_v1_jit_proto_init() {
	if File_giwa_jit_v1_jit_proto != nil {
		return
	}
	file_giwa_jit_v1_jit_proto_msgTypes[6].OneofWrappers = []any{
		(*CandidateLocator_Transaction)(nil),
		(*CandidateLocator_BlockEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_giwa_jit_v1_jit_proto_rawDesc), len(file_giwa_jit_v1_jit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_giwa_jit_v1_jit_proto_goTypes,
		DependencyIndexes: file_giwa_jit_v1_jit_proto_depIdxs,
		EnumInfos:         file_giwa_jit_v1_jit_proto_enumTypes,
		MessageInfos:      file_giwa_jit_v1_jit_proto_msgTypes,
	}.Build()
	File_giwa_jit_v1_jit_proto = out.File
	file_giwa_jit_v1_jit_proto_goTypes = nil
	file_giwa_jit_v1_jit_proto_depIdxs = nil
}
