// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: giwa/jit/v1/jit.proto

package jitv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CandidateQueryService_MaterializeAccountSelection_FullMethodName = "/giwa.jit.v1.CandidateQueryService/MaterializeAccountSelection"
)

// CandidateQueryServiceClient is the client API for CandidateQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CandidateQueryServiceClient interface {
	MaterializeAccountSelection(ctx context.Context, in *MaterializeAccountSelectionRequest, opts ...grpc.CallOption) (*MaterializeAccountSelectionResponse, error)
}

type candidateQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCandidateQueryServiceClient(cc grpc.ClientConnInterface) CandidateQueryServiceClient {
	return &candidateQueryServiceClient{cc}
}

func (c *candidateQueryServiceClient) MaterializeAccountSelection(ctx context.Context, in *MaterializeAccountSelectionRequest, opts ...grpc.CallOption) (*MaterializeAccountSelectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaterializeAccountSelectionResponse)
	err := c.cc.Invoke(ctx, CandidateQueryService_MaterializeAccountSelection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CandidateQueryServiceServer is the server API for CandidateQueryService service.
// All implementations must embed UnimplementedCandidateQueryServiceServer
// for forward compatibility.
type CandidateQueryServiceServer interface {
	MaterializeAccountSelection(context.Context, *MaterializeAccountSelectionRequest) (*MaterializeAccountSelectionResponse, error)
	mustEmbedUnimplementedCandidateQueryServiceServer()
}

// UnimplementedCandidateQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCandidateQueryServiceServer struct{}

func (UnimplementedCandidateQueryServiceServer) MaterializeAccountSelection(context.Context, *MaterializeAccountSelectionRequest) (*MaterializeAccountSelectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MaterializeAccountSelection not implemented")
}
func (UnimplementedCandidateQueryServiceServer) mustEmbedUnimplementedCandidateQueryServiceServer() {}
func (UnimplementedCandidateQueryServiceServer) testEmbeddedByValue()                               {}

// UnsafeCandidateQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CandidateQueryServiceServer will
// result in compilation errors.
type UnsafeCandidateQueryServiceServer interface {
	mustEmbedUnimplementedCandidateQueryServiceServer()
}

func RegisterCandidateQueryServiceServer(s grpc.ServiceRegistrar, srv CandidateQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedCandidateQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CandidateQueryService_ServiceDesc, srv)
}

func _CandidateQueryService_MaterializeAccountSelection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaterializeAccountSelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateQueryServiceServer).MaterializeAccountSelection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CandidateQueryService_MaterializeAccountSelection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateQueryServiceServer).MaterializeAccountSelection(ctx, req.(*MaterializeAccountSelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CandidateQueryService_ServiceDesc is the grpc.ServiceDesc for CandidateQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CandidateQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "giwa.jit.v1.CandidateQueryService",
	HandlerType: (*CandidateQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MaterializeAccountSelection",
			Handler:    _CandidateQueryService_MaterializeAccountSelection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "giwa/jit/v1/jit.proto",
}

const (
	JitEngineService_StartJitRun_FullMethodName           = "/giwa.jit.v1.JitEngineService/StartJitRun"
	JitEngineService_GetJitRun_FullMethodName             = "/giwa.jit.v1.JitEngineService/GetJitRun"
	JitEngineService_ListCandidateOutcomes_FullMethodName = "/giwa.jit.v1.JitEngineService/ListCandidateOutcomes"
	JitEngineService_RetryJitRun_FullMethodName           = "/giwa.jit.v1.JitEngineService/RetryJitRun"
)

// JitEngineServiceClient is the client API for JitEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JitEngineServiceClient interface {
	StartJitRun(ctx context.Context, in *StartJitRunRequest, opts ...grpc.CallOption) (*StartJitRunResponse, error)
	GetJitRun(ctx context.Context, in *GetJitRunRequest, opts ...grpc.CallOption) (*GetJitRunResponse, error)
	ListCandidateOutcomes(ctx context.Context, in *ListCandidateOutcomesRequest, opts ...grpc.CallOption) (*ListCandidateOutcomesResponse, error)
	RetryJitRun(ctx context.Context, in *RetryJitRunRequest, opts ...grpc.CallOption) (*RetryJitRunResponse, error)
}

type jitEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJitEngineServiceClient(cc grpc.ClientConnInterface) JitEngineServiceClient {
	return &jitEngineServiceClient{cc}
}

func (c *jitEngineServiceClient) StartJitRun(ctx context.Context, in *StartJitRunRequest, opts ...grpc.CallOption) (*StartJitRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartJitRunResponse)
	err := c.cc.Invoke(ctx, JitEngineService_StartJitRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jitEngineServiceClient) GetJitRun(ctx context.Context, in *GetJitRunRequest, opts ...grpc.CallOption) (*GetJitRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJitRunResponse)
	err := c.cc.Invoke(ctx, JitEngineService_GetJitRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jitEngineServiceClient) ListCandidateOutcomes(ctx context.Context, in *ListCandidateOutcomesRequest, opts ...grpc.CallOption) (*ListCandidateOutcomesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCandidateOutcomesResponse)
	err := c.cc.Invoke(ctx, JitEngineService_ListCandidateOutcomes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jitEngineServiceClient) RetryJitRun(ctx context.Context, in *RetryJitRunRequest, opts ...grpc.CallOption) (*RetryJitRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryJitRunResponse)
	err := c.cc.Invoke(ctx, JitEngineService_RetryJitRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JitEngineServiceServer is the server API for JitEngineService service.
// All implementations must embed UnimplementedJitEngineServiceServer
// for forward compatibility.
type JitEngineServiceServer interface {
	StartJitRun(context.Context, *StartJitRunRequest) (*StartJitRunResponse, error)
	GetJitRun(context.Context, *GetJitRunRequest) (*GetJitRunResponse, error)
	ListCandidateOutcomes(context.Context, *ListCandidateOutcomesRequest) (*ListCandidateOutcomesResponse, error)
	RetryJitRun(context.Context, *RetryJitRunRequest) (*RetryJitRunResponse, error)
	mustEmbedUnimplementedJitEngineServiceServer()
}

// UnimplementedJitEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJitEngineServiceServer struct{}

func (UnimplementedJitEngineServiceServer) StartJitRun(context.Context, *StartJitRunRequest) (*StartJitRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartJitRun not implemented")
}
func (UnimplementedJitEngineServiceServer) GetJitRun(context.Context, *GetJitRunRequest) (*GetJitRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJitRun not implemented")
}
func (UnimplementedJitEngineServiceServer) ListCandidateOutcomes(context.Context, *ListCandidateOutcomesRequest) (*ListCandidateOutcomesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCandidateOutcomes not implemented")
}
func (UnimplementedJitEngineServiceServer) RetryJitRun(context.Context, *RetryJitRunRequest) (*RetryJitRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryJitRun not implemented")
}
func (UnimplementedJitEngineServiceServer) mustEmbedUnimplementedJitEngineServiceServer() {}
func (UnimplementedJitEngineServiceServer) testEmbeddedByValue()                          {}

// UnsafeJitEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JitEngineServiceServer will
// result in compilation errors.
type UnsafeJitEngineServiceServer interface {
	mustEmbedUnimplementedJitEngineServiceServer()
}

func RegisterJitEngineServiceServer(s grpc.ServiceRegistrar, srv JitEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedJitEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JitEngineService_ServiceDesc, srv)
}

func _JitEngineService_StartJitRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartJitRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JitEngineServiceServer).StartJitRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JitEngineService_StartJitRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JitEngineServiceServer).StartJitRun(ctx, req.(*StartJitRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JitEngineService_GetJitRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJitRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JitEngineServiceServer).GetJitRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JitEngineService_GetJitRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JitEngineServiceServer).GetJitRun(ctx, req.(*GetJitRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JitEngineService_ListCandidateOutcomes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCandidateOutcomesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JitEngineServiceServer).ListCandidateOutcomes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JitEngineService_ListCandidateOutcomes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JitEngineServiceServer).ListCandidateOutcomes(ctx, req.(*ListCandidateOutcomesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JitEngineService_RetryJitRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryJitRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JitEngineServiceServer).RetryJitRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JitEngineService_RetryJitRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JitEngineServiceServer).RetryJitRun(ctx, req.(*RetryJitRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JitEngineService_ServiceDesc is the grpc.ServiceDesc for JitEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JitEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "giwa.jit.v1.JitEngineService",
	HandlerType: (*JitEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartJitRun",
			Handler:    _JitEngineService_StartJitRun_Handler,
		},
		{
			MethodName: "GetJitRun",
			Handler:    _JitEngineService_GetJitRun_Handler,
		},
		{
			MethodName: "ListCandidateOutcomes",
			Handler:    _JitEngineService_ListCandidateOutcomes_Handler,
		},
		{
			MethodName: "RetryJitRun",
			Handler:    _JitEngineService_RetryJitRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "giwa/jit/v1/jit.proto",
}
